ALTER TABLE employment
	MODIFY AreaName VARCHAR(255),
	MODIFY Title VARCHAR(255);

ALTER TABLE area
	MODIFY Areaname VARCHAR(255),
	MODIFY Area CHAR(5);

ALTER TABLE title
MODIFY Title VARCHAR(255);

ALTER TABLE crime
	MODIFY County VARCHAR(255),
	MODIFY Agency VARCHAR(255);

ALTER TABLE propertycrime
	MODIFY County VARCHAR(255),
	MODIFY Agency VARCHAR(255);
    
ALTER TABLE violentcrime
	MODIFY County VARCHAR(255),
	MODIFY Agency VARCHAR(255);
    
ALTER TABLE insurancebenefits
MODIFY County VARCHAR(255);

ALTER TABLE insuranceduration
MODIFY County VARCHAR(255);

ALTER TABLE region
	MODIFY County VARCHAR(255),
	MODIFY Region VARCHAR(255);

ALTER TABLE population
	MODIFY COLUMN Gender VARCHAR(255),
    MODIFY COLUMN RaceEthnicity VARCHAR(255),
    MODIFY COLUMN County VARCHAR(255);